backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Tech Stack", name: "stack", widget: "string"}
      - {label: "Code", name: "code", widget: "string"}
      - {label: "Live", name: "live", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: "false"}
  
  - name: "blog"
    label: "Blog"
    folder: "content/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Content", name: "content", widget: "markdown"}